export enum TestId {
  LOADING_SPINNER = 'LOADING_SPINNER',

  // Marketplace
  MARKETPLACE_PIZZA_CARD = 'MARKETPLACE_PIZZA_CARD',
  MARKETPLACE_NO_OF_ORDER_ITEMS = 'MARKETPLACE_NO_OF_ORDER_ITEMS',
  MARKETPLACE_ADD_PIZZA_TO_CART = 'MARKETPLACE_ADD_PIZZA_TO_CART',

  // Checkout
  CHECKOUT_TOTAL_PRICE = 'CHECKOUT_TOTAL_PRICE',
  CHECKOUT_PLACE_ORDER_BUTTON = 'CHECKOUT_PLACE_ORDER_BUTTON',
  CHECKOUT_EMPTY_CART_MESSAGE = 'CHECKOUT_EMPTY_CART_MESSAGE',
  CHECKOUT_ORDER_ITEM = 'CHECKOUT_ORDER_ITEM',
  CHECKOUT_REMOVE_ORDER_ITEM = 'CHECKOUT_REMOVE_ORDER_ITEM',

  // Past orders
  PAST_ORDERS_ORDER = 'PAST_ORDERS_ORDER',
  PAST_ORDERS_NO_ORDERS_MESSAGE = 'PAST_ORDERS_NO_ORDERS_MESSAGE',
}
