export enum TestId {
  LOADING_SPINNER = 'LOADING_SPINNER',
  MARKETPLACE_PIZZA_CARD = 'MARKETPLACE_PIZZA_CARD',

  // Checkout
  CHECKOUT_TOTAL_PRICE = 'CHECKOUT_TOTAL_PRICE',
  CHECKOUT_PLACE_ORDER_BUTTON = 'CHECKOUT_PLACE_ORDER_BUTTON',
  CHECKOUT_EMPTY_CART_MESSAGE = 'CHECKOUT_EMPTY_CART_MESSAGE',
  CHECKOUT_ORDER_ITEM = 'CHECKOUT_ORDER_ITEM',
}
