name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  # TODO: currently all steps are in sequence -> check how to split into several jobs that can run in parallel
  build-test-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Generate order-service API client code
        run: ./openapi-codegen.sh

      - name: Install dependencies
        run: | 
          cd frontend
          npm install

      - name: Run unit and integration tests
        run: |
          cd frontend
          CI=true npm test

      - name: Run e2e tests
        run: |
          cd frontend
          npm run build
          npm run serve
          npm run cypress:run -- --config baseUrl=http://localhost:8000

      # TODO: build, test and deploy backend to Heroku

      - name: Deploy frontend to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pizza-time-frontend"
          heroku_email: "yannickstreit@hotmail.com"
          appdir: "frontend/build"

      # TODO: run environment smoke e2e tests against test environment