name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: test frontend
        run: |
          cd frontend
          npm install
          npm test

      - name: e2e
        run: |
          cd frontend
          npm run start:ci
          npm run cypress:run