name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: unit and integration tests
        run: |
          cd frontend
          npm install
          npm test

      - name: e2e tests
        run: |
          cd frontend
          npm run build
          npm run serve
          npm run cypress:run -- --config baseUrl=http://localhost:8000