name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: | 
          cd frontend
          npm install

      - name: Run unit and integration tests
        run: |
          cd frontend
          CI=true npm test

      - name: Run e2e tests
        run: |
          cd frontend
          npm run build
          npm run serve
          npm run cypress:run -- --config baseUrl=http://localhost:8000